apiVersion: apps/v1
kind: Deployment
metadata:
  name: onenode-mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onenode-mssql
  template:
    metadata:
      labels:
        app: onenode-mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: onenode-mssql-host
      securityContext:
        fsGroup: 10001
      containers:
        - name: onenode-mssql-container
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "zaQ@1234"
              # valueFrom:
              #   secretKeyRef:
              #     name: mssql
              #     key: SA_PASSWORD
          volumeMounts:
            - name: onenode-mssql-container-data
              mountPath: /var/opt/data
      volumes:
        - name: onenode-mssql-container-data
          persistentVolumeClaim:
            claimName: onenode-mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: onenode-mssql-service
spec:
  selector:
    app: onenode-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
