apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-opensearch-dashboard
spec:
  rules:
  - host: kibana.doitsu.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-kibana-kibana
            port:
              number: 5601 
