apiVersion: v1
kind: Secret
metadata:
  name: internal-users-config
  labels:
    app: opensearch
data:
  internal_users.yml: |-
   {{ .Files.Get "secret-values/security/internal_users_value.yml" | b64enc }}