apiVersion: v1
kind: Secret
metadata:
  name: roles-mapping-config
  labels:
    app: opensearch
data:
  roles_mapping.yml: |-
   {{ .Files.Get "secret-values/security/roles_mapping_value.yml" | b64enc }}