apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opensearch-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: "https"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: opensearch-cluster-master
            port:
              number: 9200
        pathType: Exact
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: opensearch-dashboard-ingress
#   annotations:
#     kubernetes.io/ingress.class: azure/application-gateway
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /dashboard/
#         backend:
#           service:
#             name: opensearch-dashboard-opensearch-dashboards
#             port:
#               number: 5601
#         pathType: Exact