apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: http
    port: 15672
    targetPort: 15672
    nodePort: 32202
  - name: amqp
    port: 5672
    targetPort: 5672
    nodePort: 32203
  type: NodePort