kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: local 
spec:
  storageClassName: postgres
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc 
spec:
  storageClassName: postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi