#
# deploy database image to kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:13.4
          args: ["-c", "max_connections=1000", "-c", "shared_buffers=1024MB"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Abc@123456
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage 
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
              claimName: postgres-pvc
 