apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    name: rabbitmq
data:
  rabbitmq.conf: |-
    loopback_users.guest = false
    log.console = true
    log.console.level = debug
    log.exchange = true
    log.exchange.level = debug
  enabled_plugins: |-
    [rabbitmq_management].

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9-management
          ports:
            - containerPort: 15672
              name: http
            - containerPort: 5672
              name: amqp
          volumeMounts:
            - name: rabbitmq-config-map
              mountPath: /etc/rabbitmq
            - name: rabbitmq-storage
              mountPath: /data
      volumes:
        - name: rabbitmq-config-map
          configMap:
            name: rabbitmq-config
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc