apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-db
spec: 
  selector:
    app: postgres-db
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 31101
  type: NodePort