repositories:
  - name: jetstack
    url: https://charts.jetstack.io
    
releases:  
  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.7.1
    namespace: "cert-manager"
    forceNamespace: "cert-manager"
    values:
      - installCRDs: true
        extraArgs:
          - --cluster-resource-namespace=cert-manager
        global:
          logLevel: 2