#
# deploy image to kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: elasticsearch-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
        containers:
          - name: elasticsearch
            image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
            ports:
              - containerPort: 9200
            env:
                - name: discovery.type
                  value: single-node
                - name: ES_JAVA_OPTS
                  value: -Xms512m -Xmx512m
            volumeMounts:
            - mountPath: /var/lib/elasticsearch/data
              name: elasticsearch-storage
        volumes:
          - name: elasticsearch-storage
            persistentVolumeClaim:
               claimName: elasticsearch-pvc 
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    app: elasticsearch
spec: 
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
      nodePort: 30200
  type: NodePort