#
# deploy image to kubernetes
#
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kibana-deployment
  labels:
    app: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec: 
        containers:
          - name: kibana
            image: docker.elastic.co/kibana/kibana:7.15.2
            ports:
              - containerPort: 5601
            env:
               - name: ELASTICSEARCH_HOSTS
                 value: 'http://elasticsearch-service:9200'
            volumeMounts:
            - mountPath: /var/lib/kibana/data
              name: elasticsearch-storage
        volumes:
          - name: elasticsearch-storage
            persistentVolumeClaim:
               claimName: elasticsearch-pvc 

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      protocol: TCP
      targetPort: 5601
      nodePort: 30201
  type: NodePort