kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv
  labels:
    type: local 
spec:
  storageClassName: elastic
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elasticsearch-pv"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-pvc 
spec:
  storageClassName: elastic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi