kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    type: local 
spec:
  storageClassName: redis
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/redis-pv"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
spec:
  storageClassName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi